const books = [
  {
    "id": 1,
    "image": "https://carturesti.md/img-prod/214046768-0-240.png",
    "category": "Romance",
    "name": "Studentul cersetor",
    "author": "Osamu Dazai",
    "price": "151 Lei",
    "rating": 4,
    "ratingCount": 4,
    "publisher": "Humanitas",
    "quantity": 0,
    "description": "A poignant tale of a marginalized young man struggling to find his place in a cold, indifferent society, marked by shame, introspection, and an aching desire for dignity."
  },
  {
    "id": 2,
    "image": "https://carturesti.md/img-prod/601329-0-240.jpeg",
    "category": "Queer",
    "name": "Dezradacinare",
    "author": "Sasa Zare",
    "price": "279 Lei",
    "rating": 4,
    "ratingCount": 16,
    "publisher": "Trei",
    "quantity": 0,
    "description": "A heartfelt exploration of identity, dislocation, and queer existence in a world that often refuses to understand or accept difference."
  },
  {
    "id": 3,
    "image": "https://carturesti.md/img-prod/846404-0-240.jpeg",
    "category": "Culinary",
    "name": "Retete pentru pofticiosi",
    "author": "Valeria Turcan",
    "price": "590 Lei",
    "rating": 5,
    "ratingCount": 26,
    "publisher": "Humanitas",
    "quantity": 0,
    "description": "A delicious collection of classic and modern recipes crafted to delight food lovers with every bite. A must-have for passionate home cooks."
  },
  {
    "id": 4,
    "image": "https://carturesti.md/img-prod/851628-0-240.jpeg",
    "category": "Biography",
    "name": "Nu ma poti rani",
    "author": "Adam Silvera",
    "price": "273 Lei",
    "rating": 4,
    "ratingCount": 44,
    "publisher": "Trei",
    "quantity": 0,
    "description": "A raw, vulnerable memoir that confronts pain, resilience, and emotional recovery with unflinching honesty and strength."
  },
  {
    "id": 5,
    "image": "https://carturesti.md/img-prod/16701-0-240.jpeg",
    "category": "Biography",
    "name": "27 de pasi",
    "author": "Tibi Useriu",
    "price": "168 Lei",
    "rating": 3,
    "ratingCount": 16,
    "publisher": "Trei",
    "quantity": 0,
    "description": "From prison to the Arctic Circle, this is the extraordinary journey of a man who conquered his past and found redemption through endurance."
  },
  {
    "id": 6,
    "image": "https://carturesti.md/img-prod/230782-0-240.jpeg",
    "category": "Thriller",
    "name": "Deserter",
    "author": "Junji Ito Story Collection",
    "price": "519 Lei",
    "rating": 3,
    "ratingCount": 12,
    "publisher": "Humanitas",
    "quantity": 0,
    "description": "A chilling collection of psychological horror stories by the master of manga horror, where the grotesque and the surreal haunt every page."
  },
  {
    "id": 7,
    "image": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1652337322i/61077978.jpg",
    "category": "Romance",
    "name": "Migratii",
    "author": "Charlotte McConaghy",
    "price": "287 Lei",
    "rating": 4,
    "ratingCount": 25,
    "publisher": "Humanitas",
    "quantity": 0,
    "description": "Pamântul, intr-un viitor nu prea indepartat. Optzeci la suta din speciile de animale au disparut. Rândunicile-de-mare arctice migreaza dintr-o emisfera in alta, din zona arctica in Antarctica si inapoi, odata cu schimbarea celor doua anotimpuri polare. In calatoria lor, sunt conditionate de gasirea putinelor bancuri de peste ramase in oceane. Si se pare ca se afla la ultima lor migratie, dupa care si ele vor disparea."
  },
  {
    "id": 8,
    "image": "https://carturesti.md/img-prod/136102-0-240.jpeg",
    "category": "Education",
    "name": "Test your English.",
    "author": "Irina Sajina, Lorina Bujor",
    "price": "22 Lei",
    "rating": 5,
    "ratingCount": 28,
    "publisher": "Niculescu",
    "quantity": 0,
    "description": "A practical workbook packed with grammar and vocabulary exercises, ideal for learners aiming to sharpen their English language skills."
  },
  {
    "id": 9,
    "image": "https://cdn.librarius.md/img/original/find-me_1707067327.jpg",
    "category": "Queer",
    "name": "Find Me",
    "author": "Andre Aciman",
    "price": "270 Lei",
    "rating": 5,
    "ratingCount": 42,
    "publisher": "Niculescu",
    "quantity": 0,
    "description": "Years after their first love, Elio and Oliver face new passions and lingering memories that pull them back toward each other in this lyrical sequel to 'Call Me by Your Name'."
  },
  {
    "id": 10,
    "image": "https://carturesti.md/img-prod/27429-0-240.jpeg",
    "category": "Thriller",
    "name": "Lance",
    "author": "Vladimir Nabokov",
    "price": "34 Lei",
    "rating": 4,
    "ratingCount": 25,
    "publisher": "Nemira",
    "quantity": 0,
    "description": "A speculative short story by Nabokov blending science fiction and existential reflection, full of linguistic beauty and philosophical tension."
  },
  {
    "id": 11,
    "image": "https://carturesti.md/img-prod/214046111-0-240.jpeg",
    "category": "Religion",
    "name": "Intre Freud si Hristos",
    "author": "Savatie Bastovoi",
    "price": "151 Lei",
    "rating": 2,
    "ratingCount": 43,
    "publisher": "Niculescu",
    "quantity": 0,
    "description": "An introspective dialogue between psychology and faith, exploring the spiritual dimension of the human soul through both Freudian and Christian lenses."
  },
  {
    "id": 12,
    "image": "https://carturesti.md/img-prod/55321-0-240.jpeg",
    "category": "Fantasy",
    "name": "Revolta",
    "author": "Suzanne Collins",
    "price": "195 Lei",
    "rating": 5,
    "ratingCount": 53,
    "publisher": "Arthur",
    "quantity": 0,
    "description": "The thrilling conclusion to The Hunger Games trilogy, where Katniss Everdeen becomes the reluctant leader of a revolution against a tyrannical Capitol."
  },
  {
    "id": 13,
    "image": "https://media.elefant.ro/mnresize/1000/-/is/product-images/cartero/2aecdf98/2bd7/4dbf/885e/3ad1b19d1ec5/2aecdf98-2bd7-4dbf-885e-3ad1b19d1ec5_1.jpg",
    "category": "Thriller",
    "name": "Haunting Adeline",
    "author": "H. D. Carlton",
    "price": "386 Lei",
    "rating": 3,
    "ratingCount": 41,
    "publisher": "Niculescu",
    "quantity": 0,
    "description": "An intense dark romance where a writer inherits a haunted mansion and uncovers a disturbing mystery—and a mysterious stalker with twisted intentions."
  },
  {
    "id": 14,
    "image": "https://carturesti.md/img-prod/110742026-0-240.png",
    "category": "Romance",
    "name": "Asap",
    "author": "Axie Oh",
    "price": "53 Lei",
    "rating": 4,
    "ratingCount": 29,
    "publisher": "Epica",
    "quantity": 0,
    "description": "A fun and heart-fluttering K-pop-infused romance that captures the magic of first love, fame, and friendship."
  },
  {
    "id": 15,
    "image": "https://carturesti.md/img-prod/135334146-0-240.jpeg",
    "category": "Thriller",
    "name": "Un animal salbatic",
    "author": "Joel Dicker",
    "price": "231 Lei",
    "rating": 4,
    "ratingCount": 12,
    "publisher": "Epica",
    "quantity": 0,
    "description": "A suspenseful mystery set in a quiet town where secrets unravel, and the line between predator and prey blurs dramatically."
  },
  {
    "id": 16,
    "image": "https://carturesti.md/img-prod/838553-0-240.png",
    "category": "Queer",
    "name": "The First to Die at the End",
    "author": "Adam Silvera",
    "price": "443 Lei",
    "rating": 3,
    "ratingCount": 14,
    "publisher": "Epica",
    "quantity": 0,
    "description": "A moving prequel to 'They Both Die at the End', following two teens who meet on the eve of a system that predicts death launching—and the life-changing bond they form."
  },
  {
    "id": 17,
    "image": "https://carturesti.md/img-prod/55305-0-240.jpeg",
    "category": "Fantasy",
    "name": "Sfidarea",
    "author": "Suzanne Collins",
    "price": "168 Lei",
    "rating": 5,
    "ratingCount": 31,
    "publisher": "Arthur",
    "quantity": 0,
    "description": "The second installment in The Hunger Games trilogy, where Katniss and Peeta return to the deadly arena amid rising rebellion and political unrest."
  },
  {
    "id": 18,
    "image": "https://carturesti.md/img-prod/171413005-0-240.png",
    "category": "Justice",
    "name": "Codex Constitutional",
    "author": "Stefan Deaconu",
    "price": "499",
    "rating": 4,
    "ratingCount": 21,
    "publisher": "Epica",
    "quantity": 0,
    "description": "An essential legal reference that compiles Romania’s constitutional framework, offering analysis, commentary, and updated interpretations for scholars and professionals."
  },
  {
    "id": 19,
    "image": "https://carturesti.md/img-prod/214046369-0-240.png",
    "category": "Religion",
    "name": "Daca ochiul tau este curat",
    "author": "Savatie Bastovoi",
    "price": "129 Lei",
    "rating": 2,
    "ratingCount": 12,
    "publisher": "Arthur",
    "quantity": 0,
    "description": "A spiritual meditation on inner purity and perception, inviting readers to reflect on how a clean gaze can reveal divine clarity in the world."
   }, 
   {
        id: 20,
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1631816305i/1923820.jpg",
        category: "Religion",
        name: "The Holy Bible",
        author: "Anonymous",
        price: "69 Lei",
        rating: 1,
        ratingCount: 99,
        publisher: "Humanitas",
        quantity: 0,
        description: "Biblija ili Sveto pismo jest zbirka knjiga koje Hebreji i kršćani na svoj način smatraju svetima. Dijeli se u dva velika dijela: Stari i Novi zavjet.Kršćani Bibliju proučavaju kao svoju normativnu, za život smjerodavnu knjigu u kojoj oni nalaze poruku - riječ Božju. "
    },
    {
        id: 21,
        image: "https://carturesti.md/img-prod/136102-0-240.jpeg",
        category: "Education",
        name: "Test your English",
        author: "Irina Sajina, Lorina Bujor",
        price: "22 Lei",
        rating: 5,
        ratingCount: 28,
        publisher: "Niculescu",
        quantity: 0,
        description: "Varied vocabulary tests with answers; new to the popular English Vocabulary in Use series. Varied vocabulary tests with answers; new to the popular English Vocabulary in Use series."
    },
    {
        id: 22,
        image: "https://carturesti.md/img-prod/848659-0-240.jpeg",
        category: "Economy",
        name: "Societate si economie",
        author: "Mark Granovetter",
        price: "188 Lei",
        rating: 4,
        ratingCount: 12,
        publisher: "Niculescu",
        quantity: 0,
        description: "Volumul al treilea din seria Marea enciclopedie a cunoasterii ne ofera o imagine de ansamblu a societatii omenesti din perspectiva sociala, politica si economica. Rolul politicii si al institutiilor sale este acela de a stabili reguli cu caracter de obligativitate pentru o comunitate nationala, de a le impune ca universal valabile si de a le executa. Volumul al treilea din seria Marea enciclopedie a cunoasterii ne ofera o imagine de ansamblu a societatii omenesti din perspectiva sociala, politica si economica. Rolul politicii si al institutiilor sale este acela de a stabili reguli cu caracter de obligativitate pentru o comunitate nationala, de a le impune ca universal valabile si de a le executa. "
    },
    {
        id: 23,
        image: "https://carturesti.md/img-prod/27429-0-240.jpeg",
        category: "Thriller",
        name: "Lance",
        author: "Vladimir Nabokov",
        price: "34 Lei",
        rating: 4,
        ratingCount: 25,
        publisher: "Nemira",
        quantity: 0,
        description: "W"
    },
    {
        id: 24,
        image: "https://carturesti.md/img-prod/214046111-0-240.jpeg",
        category: "Religion",
        name: "Intre Freud si Hristos",
        author: "Savatie Bastovoi",
        price: "151 Lei",
        rating: 2,
        ratingCount: 43,
        publisher: "Niculescu",
        quantity: 0,
        description: "X"
    },
    {
        id: 25,
        image: "https://carturesti.md/img-prod/55321-0-240.jpeg",
        category: "Fantasy",
        name: "Revolta",
        author: "Suzanne Collins",
        price: "195 Lei",
        rating: 5,
        ratingCount: 53,
        publisher: "Arthur",
        quantity: 0,
        description: "Y"
    },
    {
        id: 26,
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1390269927i/4443485.jpg",
        category: "Culinary",
        name: "The Flavor Bible",
        author: "Andrew Dornenburg",
        price: "846 Lei",
        rating: 4,
        ratingCount: 11,
        publisher: "Niculescu",
        quantity: 0,
        description: "Great cooking goes beyond following a recipe--it's knowing how to season ingredients to coax the greatest possible flavor from them. Drawing on dozens of leading chefs' combined experience in top restaurants across the country, Karen Page and Andrew Dornenburg present the definitive guide to creating deliciousness in any dish."
    },
    {
        id: 27,
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1333580868i/13414492.jpg",
        category: "Culinary",
        name: "Flour Water Salt Yeast",
        author: "Ken Forkish",
        price: "633 Lei",
        rating: 4,
        ratingCount: 19,
        publisher: "Epica",
        quantity: 0,
        description: "From Portland's most acclaimed and beloved baker comes this must-have baking guide, featuring recipes for world-class breads and pizzas and a variety of schedules suited for the home baker."
    },
    {
        id: 28,
        image: "https://carturesti.md/img-prod/135334146-0-240.jpeg",
        category: "Thriller",
        name: "Un animal salbatic",
        author: "Joel Dicker",
        price: "231 Lei",
        rating: 4,
        ratingCount: 12,
        publisher: "Epica",
        quantity: 0,
        description: "CD"
    },
    {
        id: 29,
        image: "https://carturesti.md/img-prod/838553-0-240.png",
        category: "Queer",
        name: "The First to Die at the End",
        author: "Adam Silvera",
        price: "443 Lei",
        rating: 3,
        ratingCount: 14,
        publisher: "Epica",
        quantity: 0,
        description: "EF"
    },
    {
        id: 30,
        image: "https://cdn.librarius.md/img/original/kogda-ya-vernusi-budi-doma_1513860292.jpg",
        category: "Queer",
        name: "When I return be at home",
        author: "Elchin Safarli",
        price: "160 Lei",
        rating: 5,
        ratingCount: 31,
        publisher: "Arthur",
        quantity: 0,
        description: "LM"
    },
    {
        id: 31,
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1682429995i/141097766.jpg",
        category: "Romance",
        name: "Simon",
        author: "Narine Abgarian",
        price: "176 Lei",
        rating: 5,
        ratingCount: 24,
        publisher: "Humanitas",
        quantity: 0,
        description: "Un secol de istorie armeana, vazut prin prisma femeilor dintr-un orasel de munte, se desfasoara in Simon, noul bestseller international al scriitoarei Narine Abgarian. Simon ne atrage intr-un vartej de povesti, in care duritatea vietii se ingemaneaza cu delicatetea iubirii, iar tragicul si sumbrul se intretes cu umorul si exuberanta."
    },
    {
        id: 32,
        image: "https://cdn.librarius.md/img/original/devochka-v-nulevoy-stepeni_1680009636.jpg",
        category: "Queer",
        name: "Girl to the Zero Power",
        author: "Mikita Franko",
        price: "106 Lei",
        rating: 4,
        ratingCount: 10,
        publisher: "Arthur",
        quantity: 0,
        description: "MI"
    }
];